### ISSUE TITLE
add suport for data_bags

### ISSUE THREAD

**Issue by arosenhagen** [iain/roundsman#12]
Support for (encrypted) databags would be very nice.
There are some forks out there, but I can't try them.

when I try to install the gems with

``` bash
bundle install
rake install
```

I get the following error when running cap -T:

``` bash
cannot load such file -- roundsman/capistrano (LoadError)
```

**Comment by Arie** [comment]
Data bags support was just added in ba53ddc577231b5e600ea9828ee8862c95ecc32f
