### ISSUE TITLE
[BUG] Update chef version to > 10.16 (or don't specify the version at all)

### ISSUE THREAD

**Issue by niko** [iain/roundsman#13]
Roundsman specifies chef version 0.10.8 while chef doesn't specify the moneta version at all: http://tickets.opscode.com/browse/CHEF-3721 Chef versions < 10.16.4 break with all moneta versions > 0.7.0. Either Roundsman should upgrade the chef version or follow chefs practice of not specing the version at all.

As workaround I've set the chef version in capistrano:

```
set :chef_version, '~> 10.18'
```

**Comment by Arie** [comment]
Thanks, default chef version is now 10.18.2, fixed in commit 9287376668c254fb7c2a995a3c25c2ec0663162
